<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>数据分析</AssemblyName>
    <RootNamespace>DataAnalysis</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Costura.Fody" Version="5.7.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\index.html" />
    <EmbeddedResource Include="$(NuGetPackageRoot)microsoft.web.webview2\1.0.2792.45\runtimes\win-x86\native\WebView2Loader.dll">
      <LogicalName>WebView2Loader.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>